### ISSUE TITLE
`Error: requires absolute file path` not informative for end user

### ISSUE THREAD

**Issue by praveenkumar** [fabric8-analytics/cli-tools#37]
```
$ ./crda analyse  
Error: requires absolute file path	
Usage:
  crda analyse [flags]

Flags:
  -h, --help      help for analyse
  -j, --json      Set output format to JSON.
  -v, --verbose   Detailed Analyses Report.

Global Flags:
  -d, --debug      Sets Log level to Debug.
  -c, --no-color   Toggle colors in output.

3:50PM FTL Error Executing crda command. Please raise at https://github.com/fabric8-analytics/cli-tools/issues, if issue persists. error="requires absolute file path\t"
```

This error doesn't tell end user what kind of file I need to pass for absolute path, it should tell me this file may be `go.mod` in case of go package scanning.

**Comment by deepak1725** [comment]
Readme has been updated to provide more detailed info. 
Please check https://github.com/fabric8-analytics/cli-tools/blob/main/docs/cli_README.md#crda-cli-is-a-tool-used-to-perform-dependency-stack-scanning-right-from-cli 

Please provide your feedback on this update. Thanks

**Comment by deepak1725** [comment]
@praveenkumar We just have a release that supports both absolute and relative manifest file supports.
Please check out https://github.com/fabric8-analytics/cli-tools/releases/tag/v0.1.0
