### ISSUE TITLE
Readme contain reference of `GoManifest` tool

### ISSUE THREAD

**Issue by praveenkumar** [fabric8-analytics/cli-tools#39]
When a user want to add analyse for go package and get info on readme file, it is bit confusing because it mention 2 different tools (gomanifest and crda) https://github.com/fabric8-analytics/cli-tools#tools-and-packages . Initially I thought I do need to build `gomanifest` tool myself (since it is not part of release artifact), generate the manifest file to feed `crda` tool. But looks like `crda` itself consume `gomanifest` as library and user don't need to perform that step. At least this is what I observed during the `crc` code scan which have go mod file.

```
$ ./crda analyse  ~/work/github/crc/go.mod  --verbose
Analysing your Dependency Stack! Please wait...
3:49PM INF Total packages: 		294
3:49PM INF Source code imports: 	131
3:49PM INF Direct dependencies: 	46
Verbose Report for given Stack:

Scanned 14 Dependencies and 55 Transitives, Found 0 Issues
```

**Comment by deepak1725** [comment]
@praveenkumar This Repo Hosts all crda specific CLI-Tools. For a User/Consumer, both are separate entities.

- `gomanifest` - It's a tool to generate a dependency tree for the `go ecosystem` (using go.mod). It is mostly used in VSCode CRDA Extension. Usage: `go get github.com/fabric8-...gomanifest` which enables the environment to analyse go stacks.
- `crda-cli`- Its a CLI tool by CRDA, which itself consumes `gomanifest package` for analysing go stacks `go.mod`

Please refer [CLI Readme](https://github.com/fabric8-analytics/cli-tools/blob/main/docs/cli_README.md) to learn more about CRDA CLI

**Comment by deepak1725** [comment]
Please feel free to reopen, if any confusion persists.
