### ISSUE TITLE
Not returning Proper SA get and Post failure 

### ISSUE THREAD

**Issue by sawood14012** [fabric8-analytics/cli-tools#55]
command doesnt return failre response 
ref: 
`:24PM DBG Setting Configuration files
1:24PM DBG Using config file /Users/sawood/.crda/config.yaml.

1:24PM DBG Successfully configured config files /Users/sawood/.crda/config.yaml.
1:24PM DBG Running 'crda analyse'
1:24PM DBG Executing Analyse command.
Analysing your Dependency Stack! Please wait...
1:24PM DBG Executing StackAnalyses.
1:24PM DBG Executing: IsSupportedManifestFormat
1:24PM DBG Success: IsSupportedManifestFormat
1:24PM DBG Executing: IsSupportedManifestFormat
1:24PM DBG IsSupportedManifest path=/Users/sawood/go/src/github.com/fabric8-analytics/acceptance_tests/manifests/pom.xml regex=true
1:24PM DBG Executing: Generate dependencies.txt
1:24PM DBG Clean Repo Command: /usr/local/bin/mvn --quiet clean -f /Users/sawood/go/src/github.com/fabric8-analytics/acceptance_tests/manifests/pom.xml
1:24PM DBG dependencyTree Command: /usr/local/bin/mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.0.2:tree -f /Users/sawood/go/src/github.com/fabric8-analytics/acceptance_tests/manifests/pom.xml -DoutputFile=/var/folders/sn/93tp0dv16gj22vv3k7bc69hh0000gn/T/dependencies.txt -DoutputType=dot -DappendOutput=true
1:24PM DBG Success: buildDepsTree
1:24PM DBG Executing: postRequest.
1:24PM DBG Hitting: Stack Analyses Post API.
1:24PM DBG Executing HTTPRequestMultipart.
1:24PM DBG Building API Url.
1:24PM DBG Success: Building API Url.
1:24PM DBG Success HTTPRequestMultipart.
1:24PM DBG Executing validatePostResponse.
1:24PM DBG Sending Segment Info
Usage:
  crda analyse [flags]

Flags:
  -h, --help      help for analyse
  -j, --json      Set output format to JSON.
  -v, --verbose   Detailed Analyses Report.

Global Flags:
  -m, --client string   Client [tekton/jenkins/gh-actions] (default "terminal")
  -d, --debug           Sets Log level to Debug.
  -c, --no-color        Toggle colors in output.

invalid character 'A' looking for beginning of value`

**Comment by deepak1725** [comment]
This Error is because on Invalid Token- there is Auth Failure and API is not returning a valid JSON response.
